### ISSUE TITLE
Error if you have body set to No Body

### ISSUE THREAD

**Issue by bmccord** [grunka/insomnia-plugin-request-body-hmac#2]
While using this plugin, if you have the body of a request set as "No Body", you will get the following error message:

Failed to transform request with plugins: req_16d60a29b7f841eea89200d5d223521a

The plugin should be bypassed if you don't have a body type set.

**Comment by grunka** [comment]
Corrected this in https://github.com/grunka/insomnia-plugin-request-body-hmac/commit/b2976633e63c9f74d09bfd5df6c92eaa2b3b7871. Caused by me not completely understanding how the updated object that was returned by `getBody()` worked. Should be working properly again in version 1.0.14.
